# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        
        Dialog.setWindowTitle("ViewBot")
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setAutoFillBackground(False)
        self.linkLabel = QtWidgets.QLabel(Dialog)
        self.linkLabel.setGeometry(QtCore.QRect(150, 110, 120, 31))
        self.linkLabel.setObjectName("label")
        self.linkEdit = QtWidgets.QLineEdit(Dialog)
        self.linkEdit.setGeometry(QtCore.QRect(12, 150, 371, 22))
        self.linkEdit.setObjectName("lineEdit")
        self.viewLabel = QtWidgets.QLabel(Dialog)
        self.viewLabel.setGeometry(QtCore.QRect(150, 180, 110, 31))
        self.viewLabel.setObjectName("label_2")
        self.viewEdit = QtWidgets.QLineEdit(Dialog)
        self.viewEdit.setGeometry(QtCore.QRect(10, 220, 370, 20))
        self.viewEdit.setObjectName("lineEdit_2")
        self.startButton = QtWidgets.QPushButton(Dialog)
        self.startButton.setGeometry(QtCore.QRect(10, 250, 370, 40))
        self.startButton.setObjectName("pushButton")
        self.headlessToggle = QtWidgets.QRadioButton(Dialog)
        self.headlessToggle.setGeometry(QtCore.QRect(220, 20, 161, 20))
        self.headlessToggle.setObjectName("radioButton")
        self.tabSlider = QtWidgets.QSlider(Dialog)
        self.tabSlider.setGeometry(QtCore.QRect(220, 70, 160, 20))
        self.tabSlider.setMinimum(1)
        self.tabSlider.setMaximum(5)
        self.tabSlider.setOrientation(QtCore.Qt.Horizontal)
        self.tabSlider.setObjectName("horizontalSlider")
        self.tabLabel = QtWidgets.QLabel(Dialog)
        self.tabLabel.setGeometry(QtCore.QRect(260, 50, 90, 20))
        self.tabLabel.setObjectName("label_3")
        self.browserLabel = QtWidgets.QLabel(Dialog)
        self.browserLabel.setGeometry(QtCore.QRect(60, 10, 55, 16))
        self.browserLabel.setObjectName("label_4")
        self.chromeBox = QtWidgets.QCheckBox(Dialog)
        self.chromeBox.setGeometry(QtCore.QRect(20, 40, 130, 20))
        self.chromeBox.setObjectName("checkBox")
        self.edgeBox = QtWidgets.QCheckBox(Dialog)
        self.edgeBox.setGeometry(QtCore.QRect(20, 70, 130, 20))
        self.edgeBox.setObjectName("checkBox_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.linkLabel.setText(_translate("Dialog", "Youtube Video URL:"))
        self.viewLabel.setText(_translate("Dialog", "Amount of views:"))
        self.startButton.setText(_translate("Dialog", "Start!"))
        self.headlessToggle.setText(_translate("Dialog", "Headless mode"))
        self.tabLabel.setText(_translate("Dialog", "Tab amount"))
        self.browserLabel.setText(_translate("Dialog", "Browser:"))
        self.chromeBox.setText(_translate("Dialog", "Google Chrome"))
        self.edgeBox.setText(_translate("Dialog", "Microsoft Edge"))
